# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 5.3
  - 5.4
  - 5.5

# optionally specify a list of environments, for example to test different RDBMS
env:
#  - DB=mysql

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - composer install
#  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS test;" -uroot; fi

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script:
    - phpunit --configuration phpunit.xml --coverage-text

# configure notifications (email, IRC, campfire etc)
notifications:
    email:
        on_failure: change